resolver:  nightly-2017-09-07
packages:
- location: '.'
#- location:
#    git: https://github.com/llvm-hs/llvm-hs-pretty.git
#    commit: bb56f12e348aa1e19ec6111cecd200d4e0ffced9
flags:
extra-lib-dirs:
  - '.'
ghc-options:
  lasca:
    -O0
  library:
    -O0
    -rtsopts
    -Wincomplete-patterns
    -funbox-strict-fields
#    -fprof-auto
  lasca-test:
    -O0
    -rtsopts
#    -prof
#    -auto-all
#    -caf-all
#    -Wall
#    -fforce-recomp
#    -fdefer-type-errors