resolver:  nightly-2017-04-05 #lts-6.9
packages:
- '.'
flags:
apply-ghc-options: everything
ghc-options:
  "*": -O2
  lasca:
    -O0
    -rtsopts
    -Wincomplete-patterns
#    -Wall
#    -prof
#    -fprof-auto
#    -auto-all
#    -caf-all
#    -fforce-recomp
#    -fdefer-type-errors
extra-lib-dirs:
 - /usr/local/Cellar/libffi/3.0.13/lib
 - /Users/nau/projects/lasca/lasca-compiler