resolver:  nightly-2017-04-05 #lts-6.9
packages:
- '.'
flags:
ghc-options:
  library:
    -O2
    -rtsopts
    -Wincomplete-patterns
    -fprof-auto
  lasca-test:
    -O2
    -rtsopts
    -prof
#    -auto-all
#    -caf-all
#    -Wall
#    -fforce-recomp
#    -fdefer-type-errors
extra-lib-dirs:
 - /usr/local/Cellar/libffi/3.0.13/lib
 - /Users/nau/projects/lasca/lasca-compiler