resolver:  nightly-2017-10-10
packages:
- location: '.'
#- location:
#    git: https://github.com/llvm-hs/llvm-hs-pretty.git
#    commit: ef55f63d6f55a4ab4f7cf18f29e9d60017990233
flags:
extra-lib-dirs:
  - '.'
ghc-options:
  lasca:
    -O0
  library:
    -O0
    -rtsopts
    -Wincomplete-patterns
    -funbox-strict-fields
#    -fprof-auto
  lasca-test:
    -O0
    -rtsopts
#    -prof
#    -auto-all
#    -caf-all
#    -Wall
#    -fforce-recomp
#    -fdefer-type-errors